module.exports.descriptors = [
    'Gold',
    'Souvenir',
    'Signal',
    'Tamper',
    'Academic',
    'Voyager',
    'Silent',
    'Playback',
    'Philz',
    'Sodoi',
    'Binge',
    'Peets',
    'Lavender',
    'Round to',
    'Polaris',
    '1951',
    'Victory Point',
    '1 oz'
]

module.exports.places = [
    'Beans',
    'Cafe',
    'Cafe',
    'Coffee',
    'Bakery',
    'Lab',
    'House',
    'Room',
    'Crafts',
    'Coffee & Tea',
    'Roastery',
    'Roasters',
    'Roasting Company',
    'Coffee Tasting House',
    'Bread & Coffee',
    'Coffee Roasters',
    'Coffee Company'
]